2018-11-28 11:46:39,894 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    <html>
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:46:40,116 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    <html>
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:46:44,990 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    <html>
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:46:45,652 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    <html>
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:46:46,020 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    <html>
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:46:46,461 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    <html>
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:46:50,129 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    <html>
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:47:00,223 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    <html>
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:47:01,101 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    <html>
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:47:01,675 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    <html>
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:47:02,293 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    <html>
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:47:03,118 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    <html>
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:47:03,596 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    <html>
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:47:04,033 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    <html>
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:47:04,423 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    <html>
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:47:04,713 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    <html>
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:47:05,254 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    <html>
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:47:05,546 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    <html>
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:47:11,261 INFO: Links startup [in D:\PyCharm3\Links\app\__init__.py:33]
2018-11-28 11:47:39,624 INFO: Links startup [in D:\PyCharm3\Links\app\__init__.py:33]
2018-11-28 11:48:55,320 INFO: Links startup [in D:\PyCharm3\Links\app\__init__.py:30]
2018-11-28 11:48:55,961 INFO: Links startup [in D:\PyCharm3\Links\app\__init__.py:30]
2018-11-28 13:02:11,627 INFO: Links startup [in D:\PyCharm3\Links\app\__init__.py:30]
2018-11-28 13:02:12,285 INFO: Links startup [in D:\PyCharm3\Links\app\__init__.py:30]
2018-11-28 13:03:54,674 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:30]
2018-11-28 13:03:55,377 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:30]
2018-11-28 13:04:22,432 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:30]
2018-11-28 13:04:47,235 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:30]
2018-11-28 13:04:47,933 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:30]
2018-11-28 13:10:30,290 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:10:30,992 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:12:08,510 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:12:09,228 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:12:36,883 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:12:43,994 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:12:52,657 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:12:53,412 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:16:27,950 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:20:03,793 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:20:46,197 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:22:55,654 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:23:50,017 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:26:47,772 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:26:48,491 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:29:26,959 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:29:27,633 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:30:43,236 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:30:43,704 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:30:43,922 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:30:56,655 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:30:56,905 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:32:20,859 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:32:21,562 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:33:01,811 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:33:02,538 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:34:59,783 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:35:00,517 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:39:25,861 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:39:26,549 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:56:42,886 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 14:03:39,374 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:03:40,171 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:13:26,274 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:13:27,081 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:17:06,090 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:17:06,878 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:22:44,970 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:22:45,791 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:23:20,746 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:23:21,466 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:23:50,978 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:23:51,730 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:32:50,115 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:32:50,937 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:35:28,767 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:35:29,516 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:36:26,011 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:36:26,793 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:40:06,840 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:40:24,126 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:40:24,838 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:40:57,939 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:40:58,682 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:41:10,558 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:41:32,289 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:41:41,617 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:41:42,347 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:42:49,447 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:42:50,196 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:47:52,647 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:47:53,399 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:50:07,980 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 17:46:29,740 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 17:46:30,504 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:02:32,415 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:02:33,196 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:03:25,506 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:03:33,224 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:03:33,958 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:05:51,340 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:05:52,134 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:09:08,722 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:09:09,587 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:16:14,945 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:16:15,770 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:22:52,819 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:23:04,809 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:24:16,075 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:27:37,088 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:27:37,856 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:34:39,271 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:34:40,021 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:35:21,334 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:35:22,073 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:35:58,654 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:35:59,442 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:39:15,983 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:39:16,777 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:41:02,768 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:41:03,504 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:42:04,340 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:42:05,117 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:46:38,328 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:47:57,755 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:49:46,583 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:51:00,551 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:51:18,796 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:51:19,573 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:00:37,531 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:00:38,235 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:07:59,510 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:09:20,147 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:12:51,258 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:12:52,007 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:16:24,341 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:16:50,290 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:18:53,256 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:18:53,979 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:19:21,884 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:19:22,587 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:19:47,995 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:19:48,714 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:27:30,160 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:27:30,878 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:29:07,938 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:29:08,637 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:29:17,142 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:29:46,551 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:42:45,674 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:42:46,492 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:43:25,737 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:43:45,249 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:44:33,424 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:58:42,668 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:04:35,138 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:04:35,912 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:05:03,110 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:06:19,700 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:07:34,035 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:10:44,614 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:11:38,073 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:12:13,982 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:12:14,735 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:14:54,735 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:14:55,457 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:17:07,743 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:18:46,026 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:18:46,859 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:18:53,362 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:19:51,406 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:20:04,456 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:26:04,172 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:26:04,967 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:26:07,472 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:26:08,218 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:26:54,284 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:26:55,033 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:30:41,672 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:31:30,465 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:33:05,509 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:39:10,348 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:49:29,559 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:49:30,294 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:50:08,346 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:50:14,799 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:51:01,635 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:51:11,818 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:51:12,570 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:51:46,241 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:51:49,694 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:51:54,552 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:51:55,318 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:56:13,459 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:56:14,218 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 12:57:14,325 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 12:57:15,060 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 12:57:23,344 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 12:57:24,033 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 13:21:38,215 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 13:21:39,003 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 13:35:56,546 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 13:35:57,367 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 13:46:43,197 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 13:46:43,970 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 13:46:52,091 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 13:46:52,827 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 13:47:00,796 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 13:47:01,572 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 13:47:18,103 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 13:47:18,867 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 13:48:35,487 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 13:48:36,264 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:16:14,708 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:16:15,494 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:21:36,583 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:25:39,800 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:25:40,581 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:26:37,184 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:29:41,296 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:30:31,752 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:30:49,214 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:31:08,752 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:31:19,594 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:34:15,196 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:36:28,355 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:37:42,618 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:40:18,492 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:40:19,209 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:41:23,547 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:41:58,302 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:42:48,275 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:44:57,438 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:44:58,155 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:50:06,218 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:51:57,298 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:52:23,459 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:55:33,983 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:55:34,500 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:55:34,703 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:55:45,339 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:55:46,026 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:57:10,277 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:57:11,045 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 15:15:13,373 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 16:36:42,297 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 16:36:43,044 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 17:12:49,461 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 17:12:50,211 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 17:44:32,854 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 17:44:33,567 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 18:22:31,282 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 18:22:32,075 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-30 09:02:45,022 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-30 09:02:45,761 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-30 09:12:28,126 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-30 09:53:14,473 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-30 09:53:15,208 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-30 11:39:04,603 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-30 11:39:06,012 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-30 14:14:46,940 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-30 14:14:47,673 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-30 16:03:30,687 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-30 16:03:31,523 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
