2018-11-28 11:35:26,858 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
    return render_template("index.html", title='Home Page')
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
    <hr>
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:35:27,137 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
    return render_template("index.html", title='Home Page')
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
    <hr>
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:36:33,757 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
    return render_template("index.html", title='Home Page')
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
    <hr>
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:37:50,382 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
    return render_template("index.html", title='Home Page')
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
    <hr>
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:39:06,911 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
    return render_template("base.html", title='Home Page')
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:39:26,702 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
    return render_template("base.html", title='Home Page')
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:39:27,294 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
    return render_template("base.html", title='Home Page')
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:39:27,725 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
    return render_template("base.html", title='Home Page')
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:39:28,153 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
    return render_template("base.html", title='Home Page')
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:39:28,457 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
    return render_template("base.html", title='Home Page')
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:39:28,692 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
    return render_template("base.html", title='Home Page')
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:40:53,334 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
    return render_template("base.html", title='Home Page')
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:41:02,159 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
    return render_template("base.html", title='Home Page')
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:41:02,716 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
    return render_template("base.html", title='Home Page')
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:41:03,243 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
    return render_template("base.html", title='Home Page')
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:41:03,750 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
    return render_template("base.html", title='Home Page')
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:41:22,404 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
    return render_template("base.html", title='Home Page')
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:41:39,972 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
    return render_template("base.html", title='Home Page')
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:42:32,271 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
    return render_template("base.html", title='Home Page')
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:43:06,439 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:43:07,448 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:43:07,933 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:43:10,598 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:43:10,915 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:43:11,179 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:43:11,412 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:43:11,807 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:43:12,082 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:43:12,366 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:44:46,682 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:44:47,095 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:44:47,492 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:44:47,782 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:45:04,819 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:45:05,393 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:45:05,810 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:45:09,145 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:45:09,558 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:45:09,797 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
